version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: checkout_db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"

  backend:
    build: ./cart_backend
    volumes:
      - ./cart_backend:/app
    ports:
      - "8000:8000"
    environment:
      DB_NAME: checkout_db
      DB_USER: admin_user
      DB_PASSWORD: admin123
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    command: >
      sh -c "/app/wait-for-it.sh db 5432 -- python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/cart-ui/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/cart-ui:/app
    environment:
      - NODE_ENV=development
